---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I don't necessarily know if I am comfortable calling myself a data scientist quite yet but looking back on this quarter, I can honestly say that I have been incredibly proud of my growth as a computer programmer. I remember feeling frustrated during lab 3 because I was not only having a difficult time learning each different DPLYR verbs/functions but even more difficult was finding the right combination of these functions. These difficulties kind of highlight the challenges I experienced during the early stages of the quarter; I simply did not know enough about computer programming, much less R. However, as the quarter went on, my skills and confidence continued to grow. This was most evident during our most recent Challenge assignment; Challenge 9 Before Table Formatting. I remember going through this with relative ease, being able to visualize how I want my final table or graph to look like and knew how I wanted to get there. Not only that, but I was also able to include a little bit of creativity in my graphs through searching on Google which has been an area of programming that I avoided due to my lack of confidence and fear of crashing the entire project. It may have taken me all quarter, but I think Week 9 is when it really clicked for me how valuable a skill programming truly is and how it directly applies to my major and future career. I have always had an appreciation for analyzing data, whether it'd be graphs, tables, or even just answers on a survey. Seeing it all come together, and being able to make my own graph and table during week 9 was such an enjoyable time for me. I never really thought I would get to the point where I can create my own visualization to analyze, I thought I will forever be someone who knows how to analyze them but never be able to create them, and being able to do both during lab and challenge 9 really showed me the growth I made in our class. Additionally, our week 5 lab was another turning point in my growth as a data scientist as this was the first time I really tried getting creative with my project. Yes, admittedly all I did was add some color but I really wanted to find a way to change them based on a color I inputted so I found something online and applied it. The same can be said for my Week 7 Challenge project. It was not a requirement but I really wanted to see how much I have learned and how far I have come since the start of our quarter. So, though the challenge only asked us to create a visualization of how fish conditions have varied over the duration of the study, I decided that I also wanted to show the differences between the two trips and the variability of the condition for each species of fish. Like I said in the beginning, I don't think I am comfortable calling myself a data scientist just yet, but I am incredibly proud of the growth I have been able to showcase thus far. I look forward to someday being able to live up to that title, however, and hopefully one day I can look back at this portfolio and this time see how much I have grown officially as a data scientist.
