---
title: "The Power of Efficiency"
format: html
editor: visual
---

Efficiency is normally defined as being able to achieve a goal with minimal waste, effort, or energy. With this in mind, I think the definition of efficiency in relation to statistical computing is being able to achieve your summary or visualization in the least amount of steps possible with minimal repetition. In general, when you are working efficiently, you will be able to get as much use from your code from as little input as possible. Additionally, I also believe that writing efficient code allows whomever is reading your code the chance to better easily understand what each line is doing rather than having to guess. I have always had efficiency in mind anytime I am doing work but admittedly, I had a difficult time achieving it in our class in the beginning. Right out of the gate, I instantly realized how efficiency plays a factor in coding during week 1. I remember initially coming up with a different way to get the answer to one of our problems and remember thinking that it looked messy and that there must have been a better way to do it. After receiving feedback and the solutions being posted, I quickly saw how much cleaner and more elegant the solutions were than the one I was able to come up with. So, since then, I have tried to find the most efficient way in all my projects. Of course that was not the last time I had trouble finding the most difficult code. As I have said before, one of the projects I had the hardest time with was with Lab 3 and Challenge 3. Up until that point, I felt like efficiency was fairly straight forward but I understood its complexities during this week of class. Finding the right combination of DPLYR verbs did prove to be a challenge especially when there can be some overlap between a few DPLYR verbs. Though this portion of our class did give me the hardest time, I also think this is where I grew a greater appreciation of efficiency as it started feeling like a puzzle from this point. My last moment of appreciation for writing efficient code was when we were wiring our own function. This presented its own set of challenges but I remember feeling a sense of accomplishment when I only have to write something once as opposed to 3-4 times without the function I wrote. I also gained a better appreciation for it through our weekly peer reviews. It was much easier to review someone's code when everything was tidy and efficient, especially for someone who is just starting off. Through this class, I was able to gain a better appreciation for writing code, and that won't end when our class officially wraps up.
