---
title: "Lightening Round Essays"
format: html
editor: visual
---

-   Finish the sentence with another student\'s name: \"If \[Student\] doesn\'t earn an A, then nobody should, because...\" Explain your choice and your reasoning.

If Sal and Kailyn doesn\'t earn an A, then nobody should, because their skills and interest clearly lies with programming and I believe it showed in their work. I believe both of my group mates showcased a deep understanding for most of the learning objectives we had for our class which should result in them earning an A. Additionally, I cannot express how much both have helped me grow throughout the duration of our class which is also part of the peer support and collaboration requirement of our syllabus.

-   What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

The most difficult part of the class was finding the right combination of DPLYR verbs to accomplish a specific task. I was still learning on what each of the DPLYR verbs did, especially early in the quarter, so finding the right combination proved to be more challenging.

-   What was the easiest part of the class for you? Explain why.

The easiest part of the class for me was Regression and creating graphs. Since I am in Stat 324, I have had a little bit of practice with linear models and creating graphs all semester long. So, when week 9 rolled around, not only did I fully understand the concepts we were talking about but I have had plenty of practice with these two topics by this point.

-   What part of the class surprised or interested you the most? Explain why.

What interested me the most was definitely Regression and creating tables. I am a Quantitative Analysis concentration so these topics were closer to my major and my interests. What surprised me the most about our class is how much we were able to get done in such a short amount of time. I genuinely think that I have improved so much on my skills as a programmer and I still have a hard time believing how far we have come.

-   Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

One piece of advice I would give to a student just beginning a quarter of STAT 331 is to be patient and TAKE YOUR TIME. I understand just wanting to finish the preview and practice activities as fast as possible. I also understand that sometimes we have those days where we just do not have it in us to read through all the assigned readings and watch the videos; but they really do help. Take it from someone who basically did not have much coding experience, all these assignments and readings are designed to give you a deeper understanding of these concepts, take advantage of them. But just as importantly, be kind to yourself. It can get frustrating sometimes when your code is not working or to not get the grade you want but as long as you are learning, I hope you will find it in yourself to feel good about it. This class was specifically designed with your learning in mind, we are given multiple opportunities to improve on our skills through feedback and revisions, so just try to keep that in mind and the grade will come on its own. Lastly, and this one maybe a little bit more challenging but try not to focus solely on the grade. I understand tying ones idea of success based on the grade we receive, but funnily enough, my biggest take away from this class was to not tie my own self-worth to my grades. I used to strive for 4.0s and feeling pretty terribly every time I fell short. I remember the stress it used to cause me and the affect it had on my health (physical, mental, emotional, you name it). During our classes, we were often reminded by how much our grades should actually be valued and how we should consider how much we can reasonably give for any specific task because giving 100% every time is damn near impossible. I also remember Dr. Theobold showing us a graphic of these cats that said "Comparison is the thief of joy", which I believe was a quote by Teddy Roosevelt, and that was a real eye opener for me. This class really taught me to value learning and self care, which I find ironic because one wouldn't think to learn these in a computer programming class. It may not work for everyone but letting go of the idea that you HAVE TO GET AN A every time may allow you to better focus on your growth both as a student and as a person. Good luck to any future STAT 331 students and I hope you walk away with as much as I did in this class. I will forever cherish the lessons I got both in programming and in life.
