---
title: "Lab 7: Functions and Fish"
author: "Daltzwer Oliveros"
format:
  html: 
    self-contained: true
    code-tools: true 
    code-fold: true 
execute:
  echo: true
  messages: false
  error: true
  eval: true
  warning: false
editor: visual
---

# part 1

```{r set up}
library(tidyverse)
library(here)
fish <- read_csv(here("Week 7", "Labs", "BlackfootFish.csv"))
```

# Part 2.1 Summarizing Missing Data

```{r}
fish |> 
  summarise(across(.cols = trip:species, 
                   .fns = ~ sum(is.na(.x))))
```

As we can see from the output above, weight is the only variable with missing values at 1,796.

#part 2.2

```{r, message = FALSE, warning = FALSE}
fish_missing <- fish |>
  filter(is.na(weight))

fish_missing |>
  ggplot( mapping = aes(x = as.factor(year), fill = as.factor(trip)
             )) + 
  geom_bar() +
  labs( x = "Year Marked", y = " ", fill = "Trip Number", title = "Number of Fish Marked") +
  facet_wrap( ~ section) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2))
```

# part 3.1

```{r}
rescale_01 <- function(x) {
  scaled <- (x - min(x)) / (max(x) - min(x))
  
  
  return(scaled)
}
```

# part 3.2

```{r}
rescale_01 <- function(x) {
  stopifnot(is.numeric(x))
  stopifnot(length(x) > 1)
  scaled <- (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
  
  
  return(scaled)
}
```

# part 3.3

```{r}
x <- c(1:85, NA)

scaled <- rescale_01(x)
min(scaled, na.rm = TRUE)
max(scaled, na.rm = TRUE)
```

# question 3.4

```{r}
#| layout-nrow: 2

fish <- fish |>
  mutate(scaled_length = rescale_01(length))

fish |>
  ggplot(mapping = aes(x = length)) +
  geom_histogram()

fish |>
  ggplot(mapping = aes(x = scaled_length)) +
  geom_histogram()


```

# question 3.5

```{r}
rescale_column <- function(df, column_names){
  
  df <- df |>
    mutate(across(.cols = all_of(column_names),
                  .fns =  ~ rescale_01( .x)))
  
 return(df) 
}
```

# question 3.6

```{r}
rescale_column(fish, c("length", "weight"))

```
